created PEPS docs 1st iteration
yastn/yastn pull request #4
Opened 2023-07-21 11:59 UTC by aritrasinha98

2023-07-25 12:15 UTC, marekrams requested changes
Please link new fPEPS documentation in docs/source/yastn.fpeps.rst

2023-07-25 14:12 UTC, aritrasinha98 commented
> Please link new fPEPS documentation in docs/source/yastn.fpeps.rst

I have done the linkage.

2023-07-27 16:34 UTC, aritrasinha98 commented
I think it is more or less done at the moment. You can merge now.

2023-08-19 19:54 UTC, marekrams approved these changes

2023-08-19 19:58 UTC, merged